//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple_Weather {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simple_Weather.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friday.
        /// </summary>
        public static string day_of_week_friday {
            get {
                return ResourceManager.GetString("day_of_week_friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monday.
        /// </summary>
        public static string day_of_week_monday {
            get {
                return ResourceManager.GetString("day_of_week_monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saturday.
        /// </summary>
        public static string day_of_week_saturday {
            get {
                return ResourceManager.GetString("day_of_week_saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sunday.
        /// </summary>
        public static string day_of_week_sunday {
            get {
                return ResourceManager.GetString("day_of_week_sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thursday.
        /// </summary>
        public static string day_of_week_thursday {
            get {
                return ResourceManager.GetString("day_of_week_thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string day_of_week_today {
            get {
                return ResourceManager.GetString("day_of_week_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        public static string day_of_week_tomorrow {
            get {
                return ResourceManager.GetString("day_of_week_tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tuesday.
        /// </summary>
        public static string day_of_week_tuesday {
            get {
                return ResourceManager.GetString("day_of_week_tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wednesday.
        /// </summary>
        public static string day_of_week_wednesday {
            get {
                return ResourceManager.GetString("day_of_week_wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal error.
        /// </summary>
        public static string error_general_exception {
            get {
                return ResourceManager.GetString("error_general_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not load! Turn on location services on the device or enter a zip code in the application settings..
        /// </summary>
        public static string error_no_location_disabled {
            get {
                return ResourceManager.GetString("error_no_location_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not load weather data, turn on location or enter a zip code..
        /// </summary>
        public static string error_no_location_info {
            get {
                return ResourceManager.GetString("error_no_location_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error parsing weather data, check zip code format and refresh..
        /// </summary>
        public static string error_xml_error {
            get {
                return ResourceManager.GetString("error_xml_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current.
        /// </summary>
        public static string header_current {
            get {
                return ResourceManager.GetString("header_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        public static string humidity {
            get {
                return ResourceManager.GetString("humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated .
        /// </summary>
        public static string last_updated {
            get {
                return ResourceManager.GetString("last_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes Ago.
        /// </summary>
        public static string minutes_ago {
            get {
                return ResourceManager.GetString("minutes_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application can use location data from your phone, would you like to enable this now?.
        /// </summary>
        public static string msg_box_first_run_content {
            get {
                return ResourceManager.GetString("msg_box_first_run_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Location Data.
        /// </summary>
        public static string msg_box_first_run_title {
            get {
                return ResourceManager.GetString("msg_box_first_run_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string never {
            get {
                return ResourceManager.GetString("never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Location.
        /// </summary>
        public static string settings_automatically_detect_location {
            get {
                return ResourceManager.GetString("settings_automatically_detect_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Data on Launch.
        /// </summary>
        public static string settings_automatically_download_data {
            get {
                return ResourceManager.GetString("settings_automatically_download_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Tile in Background.
        /// </summary>
        public static string settings_automatically_update_tile {
            get {
                return ResourceManager.GetString("settings_automatically_update_tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Format:.
        /// </summary>
        public static string settings_format_label {
            get {
                return ResourceManager.GetString("settings_format_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update data if older than (min):.
        /// </summary>
        public static string settings_refresh_label {
            get {
                return ResourceManager.GetString("settings_refresh_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the following zip code if automatic location services are turned off:.
        /// </summary>
        public static string settings_zip_label {
            get {
                return ResourceManager.GetString("settings_zip_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to periodically updates the Simple Weather live tile with current weather information..
        /// </summary>
        public static string task_description {
            get {
                return ResourceManager.GetString("task_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string tile_title {
            get {
                return ResourceManager.GetString("tile_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind.
        /// </summary>
        public static string wind {
            get {
                return ResourceManager.GetString("wind", resourceCulture);
            }
        }
    }
}
